#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */
require_once __DIR__ . '/tests/_bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
                [],
                require __DIR__ . '/config/test.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
